In [ ]:
import numpy as np
import pandas as pd

: 

In [ ]:
input_dim = 5
nodes = 3

: 

In [ ]:
params = {"weights" : (input_dim*nodes), "bias" : nodes}

In [ ]:
params

In [ ]:
np.ones((nodes,input_dim))

In [ ]:
np.zeros((nodes,1))

In [28]:
nodes = [2]
layers = 1

In [29]:
curr = 4
layers = 2
nodes.append(curr)

In [30]:
nodes

[2, 4]

In [31]:
nodes[layers-2]

2

In [36]:
params = {}

In [37]:
params["w1"] = [1,1]

In [41]:
df = pd.DataFrame({"col1" : [1,2,3], "col2" : [4,5,6]})
df

col1  col2
0     1     4
1     2     5
2     3     6

In [43]:
np.array(df)[0]

array([1, 4], dtype=int64)

In [44]:
np.array(np.array([[1,4],[2,5],[3,6]]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [54]:
wts = np.array([[1,2],[4,5]])
b = np.array([[5]])
x = np.array([[2,3]])

In [55]:
x.shape

(1, 2)

In [56]:
(2*1)+(3*2)+5

13

In [58]:
np.dot(wts,x.T) + b

array([[13],
       [28]])

In [5]:
np.mean([1,2])

1.5

In [6]:
# w1(11)
idx = {"layer" : 1,"node": 1,
        "input_feat" : 1 ,"bias": False}

In [8]:
if idx["bias"]:
    print("bias")
else:
    print("wts")

wts


In [49]:
from copy import deepcopy

In [50]:
params = {"w1" : [[1,2],[3,4]],"b1":[[5],[6]],
         "w2": [[7,8]],"b2":[[9]]}

In [52]:
params_copy = deepcopy(params)

In [27]:
arg = params["w"+str(1)][1-1][1-1]

In [28]:
arg = arg + 0.1

In [29]:
arg

1.1

In [53]:
params_copy["w"+str(1)][1-1] \
[1-1] += 0.1

In [54]:
params

{'w1': [[1, 2], [3, 4]], 'b1': [[5], [6]], 'w2': [[7, 8]], 'b2': [[9]]}

In [55]:
params_copy

{'w1': [[1.1, 2], [3, 4]], 'b1': [[5], [6]], 'w2': [[7, 8]], 'b2': [[9]]}

In [63]:
wts = params["w1"]
wts

[[1, 2], [3, 4]]

In [64]:
z = np.dot(wts,[[2],[2]])

In [65]:
z

array([[ 6],
       [14]])

In [66]:
params["w1"]

[[1, 2], [3, 4]]

In [75]:
params = {"w1" : [[1,2],[3,4]],"b1":[[5],[6]],
         "w2": [[7,8]],"b2":[[9]]}

params = {"w1" : [[x11,x21],[x12,x22]],"b1":[[b11],[b12]],
         "w2": [[y11,y21]],"b2":[[b21]]}

In [2]:
x = [[1,2]]

In [24]:
def summation_ (wts:np.ndarray,bias:np.ndarray,X:np.ndarray):
        z = np.dot(wts,X) + bias
        return z

In [63]:
params_ = {"w1" : [[0.1,0.1],[0.1,0.1]],"b1":[[0],[0]],
         "w2": [[0.1,0.1]],"b2":[[0]]}

In [26]:
outputs = {}

In [51]:
def forward_prop_ (X,parameters=params_)->float:
        """if params:
            parameters = params
        else:
            parameters = params_"""
        layers_ = 2
        A = X
        for l in range(1,layers_+1):
            wts = parameters["w" + str(l)]
            bias = parameters["b" + str(l)]
            A = summation_(wts,bias,A)
            outputs["a"+str(l)] = A
        return A[0][0]

In [28]:
def mse_loss (y_pred,y)->float:
    # mean squared loss
    mse = (y_pred - y)**2
    return mse

In [29]:
from copy import deepcopy

In [53]:
 def diffp(func,idx:dict,params_,*args):
        """
        :param func: function to find y_pred
        :param idx: dictionary {"layer" : <layer_no>:int,"node": <node_no>:int,
        "input_feat" : <input_feat_no>:int,"bias":<True/False>}
        :return:
        """
        y = func(params_,*args)
        delta = 0.000000000001

        if idx["bias"]:
            # update bias
            arg = "b"
        else:
            # update wts
            arg = "w"
        # Deep Copy self.params_ and add delta to req. wt or bias
        params_copy = deepcopy(params_)
        params_copy[arg + str(idx["layer"])][idx["node"] - 1] \
            [idx["input_feat"] - 1] += delta

        y1 = func(params_copy,*args)
        return (y1 - y)/delta


In [54]:
def Loss_nn (params_,X,y)->float:
    y_pred = forward_prop_(X,parameters=params_)
    loss_func = mse_loss(y_pred,y)
    return loss_func


In [55]:
# w1(11)
idx = {"layer" : 1,"node": 1,
        "input_feat" : 1 ,"bias": False}

In [56]:
X = [[8],[8]]
y = 4

In [68]:
x11 = X[1-1][1-1]

In [57]:
diffp(Loss_nn,idx,params_,X,y)

-5.88507020893303

In [59]:
y_pred = forward_prop_(X)
print(y_pred)

0.32000000000000006


In [65]:
# w2(11)
w2_11 = params_["w2"][1-1][1-1]

In [69]:
-2*(y-y_pred)*w2_11*x11

-5.888

In [70]:
def test (a,b=None):
    if not b:
        b = 5
    print(a+b)

In [76]:
params

{'w1': [[1, 2], [3, 4]], 'b1': [[5], [6]], 'w2': [[7, 8]], 'b2': [[9]]}

In [78]:
layer = 1
node = 0

In [82]:
range(len(params["w"+str(layer)][node]))

range(0, 2)

In [85]:
params["b"+str(layer)][node]

[5]